addSbtPlugin("com.eed3si9n"        % "sbt-unidoc"             % "0.3.2")
addSbtPlugin("com.typesafe.sbt"    % "sbt-ghpages"            % "0.5.3")
addSbtPlugin("com.typesafe.sbt"    % "sbt-site"               % "0.8.1")
addSbtPlugin("org.tpolecat"        % "tut-plugin"             % "0.4.0")
addSbtPlugin("com.typesafe.sbt"    % "sbt-git"                % "0.8.4")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest"            % "0.3.5")
